### ISSUE TITLE
[Errno 8] Exec format error:

### ISSUE THREAD

**Issue by waakanni** [SegataLab/viromeqc#1]
Hi,
I am getting the following error when I attempt to run the example file that came with the software.

```
% bash test.sh
Checking Database Files                                           [ -   OK  - ]
[fastq_len_filter] | 9384 / 10000 (94.0%) reads selected          [ -  DONE - ]
[SILVA_SSU]   | Bowtie2 Aligning                                  [ -  ...  - ]Fatal error running Bowtie2 on SSU rRNA. Error message:
[Errno 8] Exec format error:
'/g/scb2/bork/mocat/software/viromeqc/1.0/cmseq/cmseq/filter.py'  [ -  FAIL - ]
```
I am using the following versions of the dependencies
```
python/3.6 diamond/0.9.24 samtools/1.7 bowtie2/2.3.4.3
```
Thank you in advance for your help.

**Comment by azufre451** [comment]
Hi waakanni,  thank you for your message.

I have tried to run viromeqc with python3.6 and samtools 1.7 and all works fine. It seems that there is an issue on the filter.py script that is launched with the env python3 interpreter.

Could you check what Operating System and system architecture are you using? (the output of `uname -a` should suffice).

Also, can you verify that you have some interpreter responding at `/usr/bin/env python3` ?

best,
Moreno

**Comment by waakanni** [comment]
Hi Moreno,

Thank you for your reply.
I have tried on these different computing clusters

```
% uname -a
Linux cluster_name 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

% /usr/bin/env python3
Python 3.6.5 (default, Mar 28 2018, 10:24:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
and 

```
% uname -a
Linux cluster_name 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 % /usr/bin/env python3
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Best

**Comment by azufre451** [comment]
Everything seems in the right place.
Did you clone the repository directly from github, together with cmseq with --recurse-submodules?

Also, do you manage to run the  `filter.py` script independently? Like, if you run: 
`<path_to_viromeqc>/cmseq/cmseq/filter.py -h`

do you get any error message?

best,
Moreno

**Comment by waakanni** [comment]
Ahh that was the problem. I was cloning cmseq separately.

Sorry for the confusion and thanks for the help.

**Comment by azufre451** [comment]
No problem! Glad you managed to solve the issue!
