### ISSUE TITLE
can get the virome db: 

### ISSUE THREAD

**Issue by allen-zhan340** [SegataLab/viromeqc#10]
i failed to retrieve DB form the zenodo or dropbox ! 

can you give me another way to solve this problem? 

thanks a lot!   

![image](https://github.com/SegataLab/viromeqc/assets/73383699/c4bf5a9f-f4e2-4acc-82e2-aeb9c079cc4c)

**Comment by azufre451** [comment]
Hi allen-zhan340,

Can you access the Zenodo folder here: https://zenodo.org/record/4020594#.X1jxgGMzZDM ? 
If you can download the three .zip files, you can then decompress them in the `<viromeQC_folder>/index/` and it should be equivalent to downloading. 

If you cannot access Zenodo from your network, I can place a copy of the database somewhere for you (let me know your preferred file-sharing provider!)

**Comment by allen-zhan340** [comment]
cool!!!
I can download the three *.zip file from Zenodo.  
it's really nice of you!
