### ISSUE TITLE
Database download fails

### ISSUE THREAD

**Issue by Yasas1994** [SegataLab/viromeqc#12]
Thanks for developing viromeqc! 

I'm not able to download the database.

upon execution of `viromeQC.py --install` a .zip file is downloaded. However, the program crashes as it attempts to decompress the .zip file. I'm guessing the link to the database has expired or migrated elsewhere? can you please assist :)

**Comment by azufre451** [comment]
Hi @Yasas1994, thank you for spotting this! 

It seems the dropbox link to the DB is not responding, so the download fails. Can you try the alternative Zenodo url? Use:

`viromeQC.py --install --zenodo`

Be sure to remove the existing downloaded .zip files from the viromeqc folder before running the install (the db should be in `<viromeqc_folder>/index/`)

Let me know if this fixes the issue!

**Comment by Yasas1994** [comment]
@azufre451 Thanks for the swift reply! Yes, It works now :)
