### ISSUE TITLE
Can I turn off length and quality filtering?

### ISSUE THREAD

**Issue by ilnamkang** [SegataLab/viromeqc#2]
Hi,

Can I turn off length and quality filtering?

I'd like to use viromeqc for data trimmed already by other tools such as trimmomatic. In this case, I think filtering by viromeqc may be not necessary.

Further, it seems that the filtering step takes much time compared to bowtie2 and diamond steps because filtering uses only one thread.

Thanks.

Ilnam

**Comment by azufre451** [comment]
H Ilnam,

The filtering step also counts the number of reads in your input, and at the moment cannot be skipped. In case you can set --minlen and --minqual to 0 and this should retain all the reads you provide as input.

You are right, that step of ViromeQC only uses one thread, but if you have more than one sample you can parallelize the execution with: [https://www.gnu.org/software/parallel/](GNU Parallel).

In the next release we will try to provide an alternative option to skip the fastq_len_filter step (but this would require to count the reads in the input file anyways, so it would probably not improve ViromeQC's performance that much).

Best,
Moreno

**Comment by ilnamkang** [comment]
Parallel worked very well.

Thanks for a quick reply and useful suggestion.
