### ISSUE TITLE
Failed to retrieve DB error

### ISSUE THREAD

**Issue by xsq2022** [SegataLab/viromeqc#5]
Hi,
   When I run viromeQC.py --install , I got "Failed to retrieve DB". Could you tell me how to solve this problem? Thank you very much.

**Comment by xsq2022** [comment]
![image](https://user-images.githubusercontent.com/101613081/200174478-09a48f27-a7e4-432f-90ee-136b170e1e25.png)
I got this error

**Comment by azufre451** [comment]
Hi, thanks for getting in touch! It seems a problem related to accessing dropbox to download the ViromeQC database.

Have you tried downloading manually the db files from Zenodo instead: https://zenodo.org/record/4020594#.X1jxgGMzZDM ?

After downloading, you should extract the zip content in a folder named `index` in the same folder of ViromeQC.

Hope this fixes the problem!

**Comment by azufre451** [comment]
@xsq2022, now it is possible to use `viromeqc.py --install --zenodo` to overcome the issue with Dropbox. 
Can you try and let me know if this works for you?

Thanks for reporting the issue!

**Comment by xsq2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I will try it. Thank you very much.
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                xsq20
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/15/2022 10:51，Moreno ***@***.***> wrote： 



@xsq2022, now it is possible to use viromeqc.py --install --zenodo to overcome the issue with Dropbox.
Can you try and let me know if this works for you?
Thanks for reporting the issue!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by xsq2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        This works for me. Thank you very much!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                xsq20
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/15/2022 10:51，Moreno ***@***.***> wrote： 



@xsq2022, now it is possible to use viromeqc.py --install --zenodo to overcome the issue with Dropbox.
Can you try and let me know if this works for you?
Thanks for reporting the issue!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
